### ISSUE TITLE
text cutoff on Macs

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#25]
Sorry to keep bothering you with little things. I tested the demo with a high school student who was running Chrome on a Mac. The vector magnitude values were partly cutoff: we lost most of the first digit. Everything looks fine on my Linux and Windows boxes, but I guess the Mac is using a different font. The text area needs to be a tiny bit wider. See the screenshots below.

<img width="640" alt="word2vec-text-cutoff" src="https://user-images.githubusercontent.com/1978092/132268416-31818e37-286b-41db-a9ad-ac40d7208ea1.png">
<img width="580" alt="word2vec-text-closeup" src="https://user-images.githubusercontent.com/1978092/132268426-6a5d86e9-8b24-439a-a722-54cce5fe4754.png">

**Comment by touretzkyds** [comment]
I'm seeing the text cutoff on my Linux box as well, when the magnitude was 1.89.  We lost part of the "1".

**Comment by jxu** [comment]
This is probably the fonts used by plotly, defined in order of preference as "Open Sans", verdana, arial, sans-serif. I increased the left margin. Which fonts do you have installed?

**Comment by touretzkyds** [comment]
I think I'm just using the default fonts. I haven't tried to modify anything. Making the left margin a little bigger should do the job. Thanks.
