### ISSUE TITLE
additional semantic dimensions

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#29]
Please modify the semantic dimensions part of the demo to provide for additional dimensions as described in the draft paper. For example, there should be a dimension for royalty, a dimension for past/present (for verbs), etc.

We need a way for the user to choose two of these dimensions to label axes of the 3D plot. I think the way to do this is to have a pulldown menu with three entries: "---", "Dimension 1", and "Dimension 2". This menu should be next to the dimension name for each dimension. If we set one of these dimensions to "Dimension 1" then the pulldown menu for the previous Dimension 1 should change to "---".

Initially, "gender" is Dimension 1 and "age" is Dimension 2. So if we want "royalty" to be Dimension 2., we set its pulldown menu to Dimension 2, and the menu for "age" should automatically change to "---".

**Comment by touretzkyds** [comment]
Leave room for two user-defined semantic dimensions.

**Comment by neelpawarcmu** [comment]
Would you like to have a placeholder for these? Like we have placeholders for man, woman, king etc. in vector analogies.

**Comment by touretzkyds** [comment]
The current placeholder "enter dimension here" is fine.
