### ISSUE TITLE
prompting for copying a word into the vector display

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#31]
When the user adds a new word, or clicks on a word already present in the 3D plot, that word becomes the "active" word and is shown in red in the 3D display. When there is an active word, the user has the option of clicking in one of the six slots in the vector display in the right half of the screen, and the active word will be copied into that slot. But there is no prompting for this, so users may never discover this feature.

Here is how we will fix this: when there is an active word (red dot in the 3D display), the six labels in the vector display should turn green and flash. If the user clicks on one of those labels, the active word is copied into that slot, and all labels turn black and stop flashing. Also, if the user deactivates the active word (by clicking on the red dot, so that the dot turns black) we should also decative the six labels, turning them black again and stopping the flashing.

**Comment by neelpawarcmu** [comment]
Resolved. Tested this with some edge cases and it seems to be robust.

**Comment by neelpawarcmu** [comment]
I tried plotly functions but that seemed convoluted. I eventually used css and that did the trick really well.

**Comment by touretzkyds** [comment]
Looks good.

**Comment by touretzkyds** [comment]
Looks good!
