### ISSUE TITLE
leaving vector arithmetic mode

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#35]
If we expand the vector arithmetic panel the demo enters vector arithmetic mode so the user can try out analogies. When they collapse the panel and we go back to regular mode, the 6-row vector display is cleared, erasing the vectors for differences and sums etc. that we no longer want to display. So far, so good.

But if the user expands the vector arithmetic panel, then changes their mind and collapses it again without having actually done any vector arithmetic, the vector display is still good and we should not be clearing it.

**Comment by touretzkyds** [comment]
After discussion, we've changed the spec for what should happen when leaving vector arithmetic mode, assuming that the user has actually done some vector arithmetic. In this case we should:

- Erase the blue arrows in the 3D plot.
- Turn the blue and green nodes in the 3D plot gray.
- Clear slots 3 and 5 of the vector display if they hold arithmetic results rather than pure words. Leave the remaining slots alone. Note that in vector arithmetic mode the user still has the ability to make nodes active and copy them into the vector display. If they overwrite slots 3 or 5 with words, then we shouldn't clear those slots when exiting vector arithmetic mode.

If the user entered vector arithmetic mode and then left it again without actually doing any vector arithmetic, we shouldn't clear anything.

**Comment by neelpawarcmu** [comment]
Resolved

**Comment by touretzkyds** [comment]
Tested and verified.
