### ISSUE TITLE
numbers in the vector display

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#36]
Currently the vector display includes a column of numbers showing the magnitude of each of the six vectors being displayed. Since the vocabulary uses unit vectors, all these magnitudes are 1.0, so it's pointless to display them. However, when we go into vector arithmetic mode, the result vectors are not normalized and so it's useful to display the magnitude.

I'd like the change the display in the following way:
- In normal vector display mode we don't display magnitudes at all. Leave it blank.
- In vector arithmetic mode, we continue to display magnitudes as we're doing now. Add a title saying "Magnitude".
- In normal vector display mode, when the user has clicked on a word and made it active, we should use this space to display the dot product of the active word and each of the six words in the vector display. (The word labels also be flashing because the user might want to store the active word in one of the slots. The magnitudes should not flash.) Add a header that says "Similarity".

It would also be good if we could move the numbers from the left side of the thick colored bars to the right side, so they are close to the word labels.

**Comment by neelpawarcmu** [comment]
I was able to add most of the functionalities. Moving the thick colored bar ticks to the left side is left, but I can take care of that as well in further revisions

**Comment by neelpawarcmu** [comment]
Resolved

**Comment by neelpawarcmu** [comment]
Resolved
