### ISSUE TITLE
displaying vector values

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#41]
If we run the mouse over one of the word vectors in the vector display, we get a pop-up menu displaying the value of the component the mouse is over, and it looks like this:
````
x: 28
y: king
z: 0.04582879
````
This is confusing for naive users. Let's replace this display with the following:
````
item: king
dim: 28
value: 0.04582879
````
This may require modifying some Plotly function in order to modify the output format.

**Comment by touretzkyds** [comment]
The latest version suppresses the magnitudes in normal mode, which is good since they're all 1.00. But the label "Magnitudes" is still present. It should be hidden.

When we make a word active, the magnitude values are displayed and they look good. But the flashing red words are a bit distracting. I'm not sure what to do about this. We're making a word active for two conflicting reasons: (1) to copy it into a slot in the vector display, or (2) to measure its similarity with words already in the vector display. We should think about ways to resolve this.

In vector analogy mode, the vector magnitudes are all showing up as 1.00. This is obviously a bug.,

**Comment by touretzkyds** [comment]
I think I have a solution to the conflict mentioned above. When a word is made active, instead of flashing the words in the vector display red, we should just draw a (non-flashing) red rectangle around each one. This provides an affordance for clicking in the box, but is much less distracting than making the words themselves red and flashing. So users can click in the box if they want to copy a vector there, or ignore the boxes if they want to focus on the similarity measure.

**Comment by neelpawarcmu** [comment]
Resolved the display values on hover. I believe the above comments are for issue #31 , currently working to resolve that.

**Comment by touretzkyds** [comment]
The hover text is good now. I made some changes to the terminology in my master branch. Please pull from that.

**Comment by neelpawarcmu** [comment]
Resolved

**Comment by touretzkyds** [comment]
Looks good.
