### ISSUE TITLE
scaling circles in the 3D plot

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#43]
Currently all words in the 3D plot are shown as constant sized circles.

To enhance the 3D effect we should scale the circles by distance from the viewer, making closer ones larger and more distant ones smaller.

**Comment by touretzkyds** [comment]
Can we make the scaling a little more subtle? The nearest nodes seem too large.

**Comment by neelpawarcmu** [comment]
Resolved. Does it look good now?

**Comment by touretzkyds** [comment]
Looks good.
