### ISSUE TITLE
change to gender word list

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#45]
Delete man/woman and king/queen from the gender word list.
Add his/her.

This makes king/queen show up in the mid-region of the residual dimension, while computer shows up in the far right.

**Comment by touretzkyds** [comment]
I tried changing the word list for gender and reloading the page, but the change doesn't take effect until I click on the "submit" button next to one of the semantic dimensions, either [gender] or [age]. Why is the residual being computed correctly when the page loads?

**Comment by neelpawarcmu** [comment]
From what I saw – we were only processing the word list on button click. I changed this to process it once the page loads.

**Comment by neelpawarcmu** [comment]
This seems to be resolved from my tests

**Comment by touretzkyds** [comment]
Yes, this resolved the issue.
