### ISSUE TITLE
tweaks to analogy display

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#46]
1. When we first open the vector analogy panel, the Result field is blank. Let's put four dashes in there so it's obvious that text goes in there.
2. As soon as the user types a value into one of the three text boxes for an analogy, we should set the Result field back to four dashes. We don't want the old result laying around as they type in a new analogy.
3. When the user presses Submit or hits Enter in the third text box, we should immediately change the Result to "computing...". Then when we have the answer, which will take a few seconds, we should update the result field to display it.

**Comment by neelpawarcmu** [comment]
Pushed the updated progress on this. Working to add "computing..." functionality.

**Comment by touretzkyds** [comment]
What we have now is good enough.
