### ISSUE TITLE
changes to vector visualization display

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#48]
Currently in the Neel branch, underneath the magnified vector view, we used to display the index of the element we are looking at. That component of the display has disappeared. It needs to come back.

I'd like to make some other changes to this part of the display.
- When the demo starts out, we were displaying magnitudes to the right of to the magnified vector view, but since all the words have magnitude 1.0 we removed this part of the display. What I'd like to do instead is display the numeric value of the feature, so users will see values like 0.14 or -0.21.
- When we select an active word, we use these numbers to display the similarity scores (dot products) of that word with the six words in the feature vector display. We should keep doing this, but we should display these numbers in red boldface. When in this mode, dragging the mouse across the feature vector display will still update the magnified view vectors, but the numbers won't change because we're displaying similarity scores (in red), not vector components (in black).
- In vector analogy mode we use these numbers to display the magnitudes of the vectors in the six slots, which will not all be 1.0. These numbers should be displayed in blue boldface instead of black normal face, and again, dragging the mouse over the vectors should not update these numbers because we're not displaying vector component values in this mode.
- The label for these numbers, either "Magnitude" or "Similarity", is too large, and centered incorrectly. It should be smaller and centered over the numbers themselves, not the magnified color bars. When displaying vector components the label should be "Value".

**Comment by neelpawarcmu** [comment]
While I was working on this I was thinking we could add a bit more intuition by modifying the hover text so it displays stuff in a format similar to the vector plot. Currently the display "x:, y:, z:" might not be very intuitive.

**Comment by touretzkyds** [comment]
I agree. The hover text should match that of the main vector display.

**Comment by neelpawarcmu** [comment]
Resolved
