### ISSUE TITLE
eliminating tick marks

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#49]
We're presently displaying magnitudes and similarity scores as tick mark labels on the thick bar plot. But these tick marks look too much like minus signs, which confuses users. Changing the color of the numbers will help a bit, but it would be better if we could suppress the tick marks. Is this possible? If not, then we may want to put the numbers in parentheses, e.g., (0.35), to separate them from the tick marks. But it would be better to suppress the tick marks or change them so they don't look like minus signs.

**Comment by neelpawarcmu** [comment]
I think it is possible. Let me try and get rid of the ticks. I can also put tick marks inside the bar and invert their color, if you would like them to be present.

**Comment by touretzkyds** [comment]
I don't think the tick marks on the magnified bars serve any useful purpose, so let's get rid of them.
