### ISSUE TITLE
moving similarity and magnitude displays

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/WordEmbeddingDemo#53]
Let's leave the right side of the vector magnify plot dedicated to displaying the indexed component, with the text labels showing the component values.

On the left side of the plot we will display:
- nothing, in normal mode if there is no active node
- similarity scores in red, if there is an active node
- vector magnitudes in blue if we are in analogy mode

**Comment by neelpawarcmu** [comment]
Resolved

**Comment by neelpawarcmu** [comment]
A new functionality for adding word to the label, is discussed. For eg. If we select 'queen', the magnitude plot's left side should say: "Similarity to 'queen'". This is being resolved.
